{% set name = "emg3d" %}
{% set version = "1.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85eca29535bc89d9e1247801f7351ecdb622d6aa4f9d9d31431a1b68d2788f4c
build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - emg3d=emg3d.cli.main:main

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
    - setuptools_scm
  run:
    - python >=3.10
    - numpy
    - scipy >=1.10
    - numba
    - empymod >=2.3.2

test:
  imports:
    - emg3d
    - emg3d.inversion
    - emg3d.inversion.simpeg
    - emg3d.inversion.pygimli

about:
  home: https://emsig.xyz
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A multigrid solver for 3D electromagnetic diffusion.
  description: |
    The modeller emg3d is a multigrid solver for 3D EM diffusion with tri-axial
    electrical anisotropy. The matrix-free solver can be used as main solver or
    as preconditioner for Krylov subspace methods, and the governing equations
    are discretized on a staggered Yee grid.
  doc_url: https://emg3d.emsig.xyz
  dev_url: https://github.com/emsig/emg3d

extra:
  recipe-maintainers:
    - prisae
