{% set name = "emg3d" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c556ee42b228fa8c9b0190f0a32573839b640d67d45af230bcd2fd7ac5fa5ddb
build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - numba >=0.45.0
    - python >=3.7
    - scipy >=1.4.0

test:
  imports:
    - emg3d

about:
  home: https://emsig.github.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A multigrid solver for 3D electromagnetic diffusion.
  description: |
    The modeller emg3d is a multigrid solver for 3D EM diffusion with tri-axial
    electrical anisotropy. The matrix-free solver can be used as main solver or
    as preconditioner for Krylov subspace methods, and the governing equations
    are discretized on a staggered Yee grid.
  doc_url: https://emg3d.readthedocs.io/
  dev_url: https://github.com/emsig/emg3d

extra:
  recipe-maintainers:
    - prisae
